# Generated by Django 2.1.5 on 2019-04-09 03:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2019)])),
                ('round', models.PositiveIntegerField()),
                ('game_time', models.DateTimeField(blank=True, null=True)),
                ('goals_for', models.PositiveIntegerField(null=True)),
                ('goals_againt', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_vote', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.Fixture')),
                ('three_votes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_votes', to=settings.AUTH_USER_MODEL)),
                ('two_votes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_votes', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, verbose_name='Team Name')),
            ],
        ),
        migrations.CreateModel(
            name='VotesTally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.Teams'),
        ),
    ]
