# Generated by Django 2.1.5 on 2019-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votestally',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
