# Generated by Django 2.1.5 on 2019-04-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_weeklyvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votestally',
            name='player',
        ),
        migrations.RemoveField(
            model_name='weeklyvote',
            name='player',
        ),
        migrations.RemoveField(
            model_name='weeklyvote',
            name='round',
        ),
        migrations.DeleteModel(
            name='VotesTally',
        ),
        migrations.DeleteModel(
            name='WeeklyVote',
        ),
    ]
